// This file is automatically generated. Do not edit it directly.
// Powered by EnterCloud Managed Supabase
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://spb-t4n4wk81ksp200of.supabase.opentrust.net";
export const SUPABASE_PUBLISHABLE_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYW5vbiIsInJlZiI6InNwYi10NG40d2s4MWtzcDIwMG9mIiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3ODQyODc3MTEsImV4cCI6MjA5OTg2MzcxMX0.Q1bed_m2R7c-z_CtzFfIbvV_o8UfA9cZMZzePgx_oRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
